name = "Havoc Realm S2"
author = "minecraftbossdj,NullHarp,Blista__Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6be223f5cba00feff41faf3d1719f6cd263242f30802250516b4f2335ac0b70a"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
