name = "Havoc Realm S2"
author = "minecraftbossdj,NullHarp,Blista__Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a4ac22f89427cea8fca4d19db044e520966a605f0c469b61f34412d9a2976a2"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
