name = "Havoc Realm S2"
author = "minecraftbossdj,NullHarp,Blista__Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc5ffaf59bdb88ea73aa41d5ae693e185df8a81fe9882f79630947511c12c4fb"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
