name = "Havoc Realm S2"
author = "minecraftbossdj,NullHarp,Blista__Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f27cb8345802c02a1d140771fb3b5afcc0b02cc5f1ea5f9967ecff4fc380107"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
