name = "Havoc Realm S2"
author = "minecraftbossdj,NullHarp,Blista__Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84342c455457667fd8ceafd8b4f620ccadf7019745ff7c673cee399cb7025f57"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
